### PR TITLE
Feature: ORM Browser

### PR DESCRIPTION
**Pull request by marcj**
Added new major feature: ORM browser.

This allows users to manage the content of their database directly via the defined models. No configuration files necessary.

Features:
 - [X] Model schema
 - [X] Adding/change/remove records in one batch (using UnitOfWork)
 - [X] Filtering
 - [X] Multiple column sorting
 - [X] Migration information
 - [X] Pagination
 - [X] Editing all columns inline (changes are displayed in green)
 - [X] Adding new records (new records are displayed in yellow)
 - [x] Seeding (using faker, directly in the GUI)
 - [x] Query interface (where you can write javascript using the Query API, and result is displayed in a static table)
 - [x] CLI to start the ORM Browser server (using ts-node)

Screenshot 2021-02-10 at 03 45 38

Screenshot 2021-02-10 at 03 45 50

Screenshot 2021-02-10 at 03 46 12

Screenshot 2021-02-10 at 04 04 12

screenshot_2021-02-10_at_04 03 06

### CODE REVIEW

**Comment by marcj** [comment]
Query prompt is implemented now. With a function to open the result in a new tab and getting the JSON.

Screenshot 2021-02-10 at 19 37 53

**Comment by marcj** [comment]
Seeding functionality implemented.

Screenshot 2021-02-12 at 02 35 57

**Comment by marcj** [comment]
Directly integrated orm-browser into the framework debugger.

Screenshot 2021-02-14 at 00 53 12

**Comment by Rush** [comment]
> Seeding functionality implemented.

This is so awesome. Seeding is one of the most common problems.

**Pull request merged**
