### PR TITLE
Update lockfileVersion

### PR DESCRIPTION
**Pull request by espindola**
This is the result of running npm run bootstrap. Somehow some files
had lockfileVersion of 1 and some 2. They should all be at 2 now.

### Relinquishment of Rights

Please mark following checkbox to confirm that you relinquish all rights of your changes:

- [x] I waive and relinquish all rights regarding this changes (including code, text, and images) to Deepkit UG (limited), Germany. This changes (including code, text, and images) are under MIT license without name attribution, copyright notice, and permission notice requirement.

### CODE REVIEW

**Comment by marcj** [comment]
@espindola Thanks for this PR! It's planned to update all lockfiles in the next upcoming release soon. We upgrade with it also some deps.

**Comment by espindola** [comment]
> @espindola Thanks for this PR! It's planned to update all lockfiles in the next upcoming release soon. We upgrade with it also some deps.

Any particular reason to not update them now? (I am new to npm). I also have a TSC update that I wanted to send on top of this, but it is hard to isolate it with so many lockfiles changing.

**Comment by marcj** [comment]
Yes, it would be unnecessary.

**Comment by marcj** [comment]
Thanks! Updated in master

**Pull request closed without merging**
