### PR TITLE
Update lock files

### PR DESCRIPTION
**Pull request by espindola**
This is the result of doing a build.

### Relinquishment of Rights

Please mark following checkbox to confirm that you relinquish all rights of your changes:

- [x] I waive and relinquish all rights regarding this changes (including code, text, and images) to Deepkit UG (limited), Germany. This changes (including code, text, and images) are under MIT license without name attribution, copyright notice, and permission notice requirement.

### CODE REVIEW

**Comment by marcj** [comment]
Please no update-locks as pull-request

**Comment by espindola** [comment]
> Please no updated package-locks as pull-request

How should they be updated?

**Comment by marcj** [comment]
We do it when necessary

**Comment by espindola** [comment]
> We do it when necessary

What is the common procedure for keeping lock file updates out of unrelated changes? I did this while trying to upgrade typescript and noticed the unrelated changes.

**Comment by marcj** [comment]
the procedure is to not update typescript and not commit package-lock files

**Pull request closed without merging**
