### PR TITLE
fix(sqlite): fix off-by-one maxConnections and set maxConnections to …

### PR DESCRIPTION
**Pull request by timvandam**
### Summary of changes

- Fixes an off by one error in the amount of connections a SQLite database creates
- Always sets maxConnections to 1 when using a `:memory:` sqlite database (these do not support multiple connections)
- Adds ':memory:' to dbPath type for SQLite to make that show up with autocompletion :^)

### Relinquishment of Rights

Please mark following checkbox to confirm that you relinquish all rights of your changes:

- [x] I waive and relinquish all rights regarding this changes (including code, text, and images) to Deepkit UG (limited), Germany. This changes (including code, text, and images) are under MIT license without name attribution, copyright notice, and permission notice requirement.

### CODE REVIEW

**Comment by timvandam** [comment]
Closes #369

**Comment by timvandam** [comment]
@marcj The failing tests fail because `maxConnections` is equal to `1`, while the tests request 2 connections. Shall I make it throw when calling `getConnection()` case when `maxConnections` is equal to one and there is already a connection? Because this connection will never be released so the promise returned by `getConnection()` will never resolve

**Comment by marcj** [comment]
> Fixes an off by one error in the amount of connections a SQLite database creates

I don't think this is correct as it breaks tests when changing just that line. So either tests are incorrect (and need to be fixed too) or this change is not correct.

I've changed all the other stuff in https://github.com/deepkit/deepkit-framework/commit/3ad96787152bcc43be8b4ee200595232264a315e as I can't merge this as is

**Comment by timvandam** [comment]
> > Fixes an off by one error in the amount of connections a SQLite database creates
> 
> I don't think this is correct as it breaks tests when changing just that line. So either tests are incorrect (and need to be fixed too) or this change is not correct.
> 
> I've changed all the other stuff in [3ad9678](https://github.com/deepkit/deepkit-framework/commit/3ad96787152bcc43be8b4ee200595232264a315e) as I can't merge this as is

Yes I believe this to be an issue with the tests. You also changed these two failing tests in 3ad96787152bcc43be8b4ee200595232264a315e (now uses a sqlite file instead of :memory: db, as these allow multiple connections). However, I still think there is an off by one in the number of connections it can create here: https://github.com/timvandam/deepkit-framework/blob/master/packages/sqlite/src/sqlite-adapter.ts#L206

I also think it would be nice to have a setter for `maxConnections` as now end users can use `db.maxConnections = 10;` on memory SQLite databases which would lead to connections connected to distinct memory dbs being created.
Also, now when you call `getConnection` on an SQLite memory database I think it would create a promise that never resolves, as (I assume) that the first connection is never closed unless you call close on the database instance

**Comment by timvandam** [comment]
I've made some disk space, created a test, fixed the issue and made a new PR https://github.com/deepkit/deepkit-framework/pull/392.
Undoing the fix will cause the test to fail.

**Pull request closed without merging**
